const slides=[
{name:'Киришүү',html:`<div class="hero"><div><div class="eyebrow">Кыргыз тили · Слайд-сабак</div><h1>Этиштин<br>өзгөчө<br>формалары</h1><p class="lead">Бир кыймыл — үч башка кызмат.<br>Атоочтук, чакчыл жана кыймыл атооч менен таанышабыз.</p><span class="tag">8 слайд · Эрежелер жана мисалдар</span></div><div class="diagram"><div class="diagram-label">БИР УҢГУДАН</div><div class="root">оку<span style="color:#8caf98">—</span></div><div class="branch"><strong>оку<em>ган</em></strong><span>Атоочтук</span></div><div class="branch"><strong>оку<em>п</em></strong><span>Чакчыл</span></div><div class="branch"><strong>ок<em>уу</em></strong><span>Кыймыл атооч</span></div></div></div>`},
{name:'Үч форма',html:`<div class="eyebrow">01 · Негизги түшүнүк</div><h2>Эмне үчүн «өзгөчө»?</h2><p class="intro">Бул формалар этиштен жасалат, бирок башка сөз түркүмдөрүнө мүнөздүү белгилерге да ээ болот.</p><div class="cards"><div class="card"><small>01 / БЕЛГИ</small><h3>Атоочтук</h3><p>Кыймылды заттын белгиси катары көрсөтөт.</p><span class="word">келген конок</span><p>Кандай конок?</p></div><div class="card"><small>02 / КОШУМЧА КЫЙМЫЛ</small><h3>Чакчыл</h3><p>Негизги кыймылдын аткарылышын кошумчалайт.</p><span class="word">күлүп сүйлөдү</span><p>Кантип сүйлөдү?</p></div><div class="card"><small>03 / КЫЙМЫЛДЫН АТЫ</small><h3>Кыймыл атооч</h3><p>Кыймыл-аракеттин атын билдирет.</p><span class="word">китеп окуу</span><p>Эмне?</p></div></div>`},
{name:'Атоочтук',html:`<div class="eyebrow">02 · Атоочтук</div><div class="two"><div><h2>Кыймыл аркылуу<br>заттын белгиси</h2><p>Атоочтук заттын кандай экенин анын кыймылы аркылуу түшүндүрөт. Сын атоочко окшоп, затты аныктай алат.</p><h3>Көп колдонулган мүчөлөр</h3><div class="suffixes"><span>-ган</span><span>-ар</span><span>-бас</span><span>-уучу</span></div><p class="note">Мүчөлөр үндөшүү мыйзамына жараша өзгөрөт: келген, барган, өткөн.</p></div><div class="example"><small>СҮЙЛӨМДӨ КАРАП КӨРӨЛҮ</small><blockquote><mark>Келген</mark> конок<br>төргө отурду.</blockquote><p>Кандай конок? → келген конок.</p><p>«Келген» сөзү коноктун белгисин анын жасаган кыймылы аркылуу билдирип турат.</p></div></div>`},
{name:'Чакчыл',html:`<div class="eyebrow">03 · Чакчыл</div><div class="two"><div><h2>Негизги кыймылга<br>кошумча маани</h2><p>Чакчыл негизги кыймылдын кандайча, качан же кандай шартта аткарыларын билдирет.</p><h3>Көп колдонулган мүчөлөр</h3><div class="suffixes"><span>-ып</span><span>-а, -е, -й</span><span>-ганча</span><span>-майынча</span></div><p class="note">Мисалдар: жазып, сүйлөй, келгенче, бүтмөйүнчө.</p></div><div class="example"><small>СҮЙЛӨМДӨ КАРАП КӨРӨЛҮ</small><blockquote>Ал <mark>күлүп</mark><br>сүйлөдү.</blockquote><p>Кантип сүйлөдү? → күлүп.</p><p>Негизги кыймыл — «сүйлөдү». «Күлүп» ошол кыймылдын кандайча аткарылганын көрсөтөт.</p></div></div>`},
{name:'Кыймыл атооч',html:`<div class="eyebrow">04 · Кыймыл атооч</div><div class="two"><div><h2>Кыймылдын<br>атын атайбыз</h2><p>Кыймыл атооч аракетти атайт. Ал зат атооч сыяктуу жөндөлүп, таандык мүчөлөрдү кабыл ала алат.</p><h3>Мүчөлөрдүн мисалдары</h3><div class="suffixes"><span>-уу, -үү</span><span>-оо, -өө</span><span>-ыш, -иш</span><span>-мак, -мек</span></div><p class="note">Окуу → окуунун → окууга.<br>Жазуу → жазуум.</p></div><div class="example"><small>СҮЙЛӨМДӨ КАРАП КӨРӨЛҮ</small><blockquote><mark>Окуу</mark> —<br>пайдалуу иш.</blockquote><p>Эмне пайдалуу иш? → окуу.</p><p>Бул жерде «окуу» кыймылдын атын билдирип, сүйлөмдө ээнин милдетин аткарды.</p></div></div>`},
{name:'Салыштыруу',html:`<div class="eyebrow">05 · Салыштыруу</div><h2>Уңгу бир, кызматы башка.</h2><p>«Жаз» этишин үч түрдүү формада колдонуп көрөлү.</p><div class="table-wrap"><table><thead><tr><th>Форма</th><th>Мисал</th><th>Эмнени билдирет?</th></tr></thead><tbody><tr><td>Атоочтук</td><td><em>Жазган</em> окуучу</td><td>Окуучунун белгисин</td></tr><tr><td>Чакчыл</td><td><em>Жазып</em> отурду</td><td>Негизги кыймылга кошумча кыймылды</td></tr><tr><td>Кыймыл атооч</td><td><em>Жазуу</em> — өнөр</td><td>Кыймылдын атын</td></tr></tbody></table></div><p class="note" style="margin-top:25px">Форманы аныктоодо мүчөсүнө гана эмес, сүйлөмдөгү маанисине жана кызматына да көңүл бур.</p>`},
{name:'Көнүгүү',html:`<div class="eyebrow">06 · Өзүңдү текшер</div><h2>«Шашып» — кайсы форма?</h2><div class="example" style="max-width:780px;margin-top:28px"><blockquote style="margin:0">Бекзад мектепке <mark>шашып</mark> барды.</blockquote></div><div class="exercise"><button data-answer="no">Атоочтук</button><button data-answer="yes">Чакчыл</button><button data-answer="no">Кыймыл атооч</button></div><p class="feedback" id="feedback" role="status">Туура жоопту танда.</p>`},
{name:'Жыйынтык',html:`<div class="eyebrow">07 · Жыйынтык</div><h2>Үч суроо менен эсте сакта.</h2><div class="cards"><div class="card"><small>АТООЧТУК</small><h3>Кандай?</h3><span class="word">өскөн дарак</span><p>Заттын белгисин көрсөтөт.</p></div><div class="card"><small>ЧАКЧЫЛ</small><h3>Кантип?</h3><span class="word">шашып келди</span><p>Кыймылды кошумчалайт.</p></div><div class="card"><small>КЫЙМЫЛ АТООЧ</small><h3>Эмне?</h3><span class="word">билим алуу</span><p>Кыймылдын атын билдирет.</p></div></div><p class="note" style="margin-top:25px">Бул суроолор мисалдарды эстөөгө жардам берет; ар бир форманын сүйлөмдөгү кызматы кеңири болушу мүмкүн.</p><div class="sources">Булактар: <a href="https://orfo.el-sozduk.kg/грамматика/pb/" target="_blank" rel="noopener">Эл-Сөздүк · Этиштин өзгөчө формалары</a> · <a href="https://encyclopedia.edu.kg/KyrgWiki/index.php?title=АТООЧТУК" target="_blank" rel="noopener">Кыргыз энциклопедиясы · Атоочтук</a></div>`}
];
let current=0;const deck=document.getElementById('deck'),dots=document.getElementById('dots');
slides.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`${i+1}. ${s.name}`);b.title=s.name;b.onclick=()=>go(i);dots.append(b)});
function go(i){current=Math.max(0,Math.min(slides.length-1,i));deck.innerHTML=`<section class="slide" aria-label="${slides[current].name}">${slides[current].html}</section>`;document.getElementById('number').textContent=String(current+1).padStart(2,'0');document.getElementById('progress').style.width=`${(current+1)/slides.length*100}%`;document.getElementById('prev').disabled=current===0;document.getElementById('next').innerHTML=current===slides.length-1?'Башынан ↺':'Кийинки <span>→</span>';[...dots.children].forEach((b,j)=>{b.classList.toggle('active',j===current);b.setAttribute('aria-current',j===current?'step':'false')});history.replaceState(null,'',`#${current+1}`);deck.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='yes';b.classList.add(ok?'correct':'wrong');document.getElementById('feedback').textContent=ok?'Туура! «Шашып» — чакчыл. Кантип барды? — шашып. Ал -ып мүчөсү аркылуу жасалды.':'Дагы ойлонуп көр: «шашып» сөзү «кантип барды?» деген суроого жооп берет.'});}
document.getElementById('prev').onclick=()=>go(current-1);document.getElementById('next').onclick=()=>go(current===slides.length-1?0:current+1);
document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown','ArrowLeft','PageUp','Home','End'].includes(e.key)){e.preventDefault();go(e.key==='Home'?0:e.key==='End'?slides.length-1:current+(['ArrowRight','PageDown'].includes(e.key)?1:-1))}});
document.getElementById('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('full').textContent='Толук экран жеткиликсиз'}};
let touchX=0,touchY=0;deck.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY},{passive:true});deck.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)go(current+(dx<0?1:-1))},{passive:true});
go((Number(location.hash.slice(1))||1)-1);
